name: "Nobl9 sloctl action"
description: "Applies Nobl9 yaml configuration files using the sloctl CLI tool"
branding:
  icon: 'target'
  color: 'blue'
inputs:
  client_id:
    description: "Client ID"
    required: true
  client_secret:
    description: "Client Secret"
    required: true
  sloctl_yml:
    description: "The path or glob pattern to the configuration in YAML format"
    required: true
  auto_confirm:
    description: "Auto-confirm applying multiple files"
    required: false
    default: "false"
  dry_run:
    description: "Submits server-side request without persisting the configured resources"
    required: false
    default: "false"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.client_id }}
    - ${{ inputs.client_secret }}
    - ${{ inputs.sloctl_yml }}
    - ${{ inputs.auto_confirm }}
    - ${{ inputs.dry_run }}
